/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package collegemanagement;

import java.sql.*;
import java.util.regex.Pattern;
import javax.swing.*;

/**
 *
 * @author abc
 */
public class StudentAdmission extends javax.swing.JFrame {

    /**
     * Creates new form StudentAdmission
     */
    public StudentAdmission() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jButton1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        eno = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        name = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        dob = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        male = new javax.swing.JRadioButton();
        female = new javax.swing.JRadioButton();
        jLabel5 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        address = new javax.swing.JTextArea();
        jLabel6 = new javax.swing.JLabel();
        pqual = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        per = new javax.swing.JTextField();
        jButton2 = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        mob_text = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Student Admission");
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosed(java.awt.event.WindowEvent evt) {
                formWindowClosed(evt);
            }
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });

        jButton1.setFont(new java.awt.Font("Iskoola Pota", 3, 14)); // NOI18N
        jButton1.setText("Back");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Iskoola Pota", 3, 14)); // NOI18N
        jLabel1.setText("Enrollment no.");

        eno.setFont(new java.awt.Font("Iskoola Pota", 2, 14)); // NOI18N
        eno.setName("eno"); // NOI18N

        jLabel2.setFont(new java.awt.Font("Iskoola Pota", 3, 14)); // NOI18N
        jLabel2.setText("Name:-");

        name.setFont(new java.awt.Font("Iskoola Pota", 2, 14)); // NOI18N
        name.setName("name"); // NOI18N

        jLabel3.setFont(new java.awt.Font("Iskoola Pota", 3, 14)); // NOI18N
        jLabel3.setText("D.O.B:-");

        dob.setFont(new java.awt.Font("Iskoola Pota", 2, 14)); // NOI18N
        dob.setName("dob"); // NOI18N

        jLabel4.setFont(new java.awt.Font("Iskoola Pota", 3, 14)); // NOI18N
        jLabel4.setText("Gender:-");

        buttonGroup1.add(male);
        male.setFont(new java.awt.Font("Iskoola Pota", 2, 14)); // NOI18N
        male.setText("Male");
        male.setName("gender"); // NOI18N
        male.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                maleActionPerformed(evt);
            }
        });

        buttonGroup1.add(female);
        female.setFont(new java.awt.Font("Iskoola Pota", 2, 14)); // NOI18N
        female.setText("Female");
        female.setName("gender"); // NOI18N

        jLabel5.setFont(new java.awt.Font("Iskoola Pota", 3, 14)); // NOI18N
        jLabel5.setText("Address:-");

        jScrollPane1.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
        jScrollPane1.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_NEVER);

        address.setColumns(20);
        address.setFont(new java.awt.Font("Iskoola Pota", 2, 14)); // NOI18N
        address.setRows(5);
        address.setWrapStyleWord(true);
        address.setName("address"); // NOI18N
        jScrollPane1.setViewportView(address);

        jLabel6.setFont(new java.awt.Font("Iskoola Pota", 3, 14)); // NOI18N
        jLabel6.setText("Past Qualification:-");

        pqual.setFont(new java.awt.Font("Iskoola Pota", 2, 14)); // NOI18N
        pqual.setName("qual"); // NOI18N

        jLabel7.setFont(new java.awt.Font("Iskoola Pota", 3, 14)); // NOI18N
        jLabel7.setText("Percentage:-");

        per.setFont(new java.awt.Font("Iskoola Pota", 2, 14)); // NOI18N
        per.setName("per"); // NOI18N

        jButton2.setFont(new java.awt.Font("Iskoola Pota", 3, 14)); // NOI18N
        jButton2.setText("Submit");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jLabel8.setFont(new java.awt.Font("Iskoola Pota", 3, 14)); // NOI18N
        jLabel8.setText("Mobile No :-");

        mob_text.setFont(new java.awt.Font("Iskoola Pota", 2, 14)); // NOI18N
        mob_text.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mob_textActionPerformed(evt);
            }
        });

        jLabel9.setText("E.g. (DD/MM/YYYY)");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(55, 55, 55)
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(82, 82, 82)
                        .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 119, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel6)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2)
                            .addComponent(jLabel4)
                            .addComponent(jLabel3)
                            .addComponent(jLabel5)
                            .addComponent(jLabel7)
                            .addComponent(jLabel8))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(43, 43, 43)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(male, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(female, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(per, javax.swing.GroupLayout.DEFAULT_SIZE, 120, Short.MAX_VALUE)
                                            .addComponent(eno)
                                            .addComponent(pqual)
                                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                                            .addComponent(dob)
                                            .addComponent(name))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jLabel9)
                                        .addGap(0, 0, Short.MAX_VALUE))))
                            .addGroup(layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(mob_text, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(149, 149, 149)))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(eno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(name, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(dob, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(male)
                    .addComponent(female))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(7, 7, 7)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jLabel5)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(pqual, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel7)
                    .addComponent(per, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addComponent(jLabel8))
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(mob_text, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 35, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(5, 5, 5)
                        .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowClosed(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosed
        // TODO add your handling code here:
        
        
    }//GEN-LAST:event_formWindowClosed

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        // TODO add your handling code here:
    }//GEN-LAST:event_formWindowClosing

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
                new CollegeManagement().setVisible(true);
                this.setVisible(false);

    }//GEN-LAST:event_jButton1ActionPerformed

    private void maleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_maleActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_maleActionPerformed

      Connection con ;
    Statement st ;
    ResultSet rs ;
    String db;
    PreparedStatement prst;
    Boolean error=false;
//    public void TestConnection (){
//        try{
//            String path = "C:\\Users\\abc\\Documents\\CollegeMan.accdb";
//        db ="JDBC:ODBC:Driver=Microsoft Access Driver (*.mdb, *.accdb); DBQ="+path;
//            doConnection();
//        } catch(NullPointerException ex){
//                ex.printStackTrace();
//            }
//
//    }
    public void doConnection() { 
        error=false;
        try {
//             Class.forName("sun.jdbc.odbc.JdbcOdbcDriver");
                  con=DriverManager.getConnection("jdbc:ucanaccess://C:\\Users\\thofiq\\Documents\\CollegeMan.accdb");

//            +Integer.parseInt(eno.getText())+",'"+name.getText()+"','"+dob.getText()+"','male'
            String Query="insert into student (Enrolment_Id,Name,D_O_B,Gender,Address,Past_Qualification,Percentage,Mobile_no) Values (?,?,?,?,?,?,?,?)";
            prst = con.prepareStatement(Query);
            

            if(eno.getText().isEmpty()){
               
                JOptionPane.showMessageDialog(null, "Please Enter Enrolment no", "Alert", JOptionPane.ERROR_MESSAGE);
                error=true;
                return;
            }else{
                if(Pattern.matches("[0-9]{8}",eno.getText())){
            prst.setString(1,eno.getText());
                } else{
                 JOptionPane.showMessageDialog(null, "Please Enter Valid Enrollment no", "Alert", JOptionPane.ERROR_MESSAGE);
                   error=true;
                   return;
                }
            
            }
             if(!name.getText().isEmpty()){
             prst.setString(2,name.getText());

            }else{
             JOptionPane.showMessageDialog(null, "Please Enter Name", "Alert", JOptionPane.ERROR_MESSAGE);
                error=true;
                return;
             }
              if(!dob.getText().isEmpty()){
                  if (Pattern.matches("^[0|1|2|3][0-9]\\/([0][0-9]|[1][0-2])\\/([0|1][0-9]{3}|[2]0[0-9]{2})$",dob.getText())){
                      prst.setString(3,dob.getText());
                  }
                  else{
                  JOptionPane.showMessageDialog(null, "Please Enter valid Date of Birth", "Alert", JOptionPane.ERROR_MESSAGE);
                error=true;
                return;
                  }
               

            }else{
               JOptionPane.showMessageDialog(null, "Please Enter Date of Birth", "Alert", JOptionPane.ERROR_MESSAGE);
                error=true;
                return;
              }
            String Gender="";
            if (male.isSelected()==true){
                Gender="Male";
            }
            else if(female.isSelected()==true){
                Gender="Female";
            }
            else 
            {
                JOptionPane.showMessageDialog(null, "Please Select Gender", "Alert", JOptionPane.ERROR_MESSAGE);
                error=true;
                return;
                
            }
            prst.setString(4,Gender);
            
             if(!address.getText().isEmpty()){
                           prst.setString(5,address.getText());

            }else{
               JOptionPane.showMessageDialog(null, "Please Enter Address", "Alert", JOptionPane.ERROR_MESSAGE);
                error=true;
                return;
              }
              if(!pqual.getText().isEmpty()){
                           prst.setString(6,pqual.getText());

            }else{
               JOptionPane.showMessageDialog(null, "Please Enter Past Qualification", "Alert", JOptionPane.ERROR_MESSAGE);
                error=true;
                return;
              }
               if(!per.getText().isEmpty()){
                           prst.setFloat(7,Float.parseFloat(per.getText()));

            }else{
               JOptionPane.showMessageDialog(null, "Please Enter Percentage", "Alert", JOptionPane.ERROR_MESSAGE);
                error=true;
                return;
              }
               if(!mob_text.getText().isEmpty()){
                  
                   if(!Pattern.matches("[0-9]{10}", mob_text.getText()))
                   {
                    JOptionPane.showMessageDialog(null, "Please Enter 10 Digit Valid Mobile No", "Alert", JOptionPane.ERROR_MESSAGE);
                    error=true;
                     return;
                   }else{
                        prst.setString(8,mob_text.getText());

                       
                   }

            }else{
               JOptionPane.showMessageDialog(null, "Please Enter Mobile No", "Alert", JOptionPane.ERROR_MESSAGE);
                error=true;
                return;
              }
            
            
            if ( error==false){
                prst.execute();
                JOptionPane.showMessageDialog(null, "Successfully Submitted", "Submitted", JOptionPane.OK_OPTION);
                name.setText("");
                per.setText("");
                dob.setText("");
                address.setText("");
                pqual.setText("");
                eno.setText("");
                male.setSelected(false);
                female.setSelected(false);
                mob_text.setText("");

                
                
            }
            

            
//            st=con.createStatement();
//            st.execute(Query);
//            while(rs.next()){
//                System.out.println(rs.getInt(1));
//            }
        }catch(SQLException ex){
            System.out.println(ex.toString());

        }
        
    }
    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
            // TODO add your handling code here:
          
    
        
    
        doConnection();
        
    
       
      
        
    }//GEN-LAST:event_jButton2ActionPerformed

    private void mob_textActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mob_textActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_mob_textActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(StudentAdmission.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(StudentAdmission.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(StudentAdmission.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(StudentAdmission.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new StudentAdmission().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextArea address;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JTextField dob;
    private javax.swing.JTextField eno;
    private javax.swing.JRadioButton female;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JRadioButton male;
    private javax.swing.JTextField mob_text;
    private javax.swing.JTextField name;
    private javax.swing.JTextField per;
    private javax.swing.JTextField pqual;
    // End of variables declaration//GEN-END:variables
}
