/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package collegemanagement;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.regex.Pattern;
import javax.swing.JOptionPane;

/**
 *
 * @author abc
 */
public class UpdateStudent extends javax.swing.JFrame {

    /**
     * Creates new form UpdateStudent
     */
    public UpdateStudent() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        Enr_no = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        name_text = new javax.swing.JTextField();
        dob_text = new javax.swing.JTextField();
        addr_text = new javax.swing.JTextField();
        pqual_text = new javax.swing.JTextField();
        gender_text = new javax.swing.JTextField();
        per_text = new javax.swing.JTextField();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        mob_text = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Update Student Details");

        jButton1.setFont(new java.awt.Font("Iskoola Pota", 3, 14)); // NOI18N
        jButton1.setText("Search");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Iskoola Pota", 3, 14)); // NOI18N
        jLabel1.setText("Enter Enrolment No :-");

        Enr_no.setFont(new java.awt.Font("Iskoola Pota", 2, 14)); // NOI18N

        jLabel2.setFont(new java.awt.Font("Iskoola Pota", 3, 14)); // NOI18N
        jLabel2.setText("Name :-");

        jLabel3.setFont(new java.awt.Font("Iskoola Pota", 3, 14)); // NOI18N
        jLabel3.setText("D-O-B :-");

        jLabel4.setFont(new java.awt.Font("Iskoola Pota", 3, 14)); // NOI18N
        jLabel4.setText("Gender :-");

        jLabel5.setFont(new java.awt.Font("Iskoola Pota", 3, 14)); // NOI18N
        jLabel5.setText("Address :-");

        jLabel6.setFont(new java.awt.Font("Iskoola Pota", 3, 14)); // NOI18N
        jLabel6.setText("Past Qualification :-");

        jLabel7.setFont(new java.awt.Font("Iskoola Pota", 3, 14)); // NOI18N
        jLabel7.setText("Percentage :-");

        name_text.setFont(new java.awt.Font("Iskoola Pota", 2, 14)); // NOI18N

        dob_text.setFont(new java.awt.Font("Iskoola Pota", 2, 14)); // NOI18N

        addr_text.setFont(new java.awt.Font("Iskoola Pota", 2, 14)); // NOI18N

        pqual_text.setFont(new java.awt.Font("Iskoola Pota", 2, 14)); // NOI18N

        gender_text.setFont(new java.awt.Font("Iskoola Pota", 2, 14)); // NOI18N

        per_text.setFont(new java.awt.Font("Iskoola Pota", 2, 14)); // NOI18N

        jButton2.setFont(new java.awt.Font("Iskoola Pota", 3, 14)); // NOI18N
        jButton2.setText("Update");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setFont(new java.awt.Font("Iskoola Pota", 3, 14)); // NOI18N
        jButton3.setText("Back");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jLabel8.setFont(new java.awt.Font("Iskoola Pota", 3, 14)); // NOI18N
        jLabel8.setText("Mobile No :-");

        mob_text.setFont(new java.awt.Font("Iskoola Pota", 2, 14)); // NOI18N
        mob_text.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mob_textActionPerformed(evt);
            }
        });

        jLabel9.setText("E.g. (DD/MM/YYYY)");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 5, Short.MAX_VALUE)
                        .addComponent(Enr_no, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(30, 30, 30)
                        .addComponent(jButton1)
                        .addGap(24, 24, 24))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel4)
                            .addComponent(jLabel6)
                            .addComponent(name_text, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(pqual_text, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(gender_text, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton3, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addGap(45, 45, 45)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel9)
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(per_text, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(dob_text, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel7)
                                    .addComponent(jLabel5)
                                    .addComponent(addr_text, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jButton2))
                                .addGap(0, 0, Short.MAX_VALUE))))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel8)
                            .addComponent(mob_text, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(jLabel1)
                    .addComponent(Enr_no, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3)
                    .addComponent(jLabel9))
                .addGap(5, 5, 5)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(name_text, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(dob_text, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jLabel5))
                .addGap(10, 10, 10)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(addr_text, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(gender_text, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(jLabel7))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(pqual_text, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(per_text, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel8)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(mob_text, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton2)
                    .addComponent(jButton3))
                .addGap(20, 20, 20))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
         new CollegeManagement().setVisible(true);
                this.setVisible(false);
    }//GEN-LAST:event_jButton3ActionPerformed

    
    
    Connection con ;
    Statement st ;
    ResultSet rs ;
    String db;
    PreparedStatement prst;
    Boolean error=false;
    public void searchStudent(){
        Boolean val=false;
        if (Enr_no.getText().isEmpty()){
        JOptionPane.showMessageDialog(null, "Please Enter Enrolment no", "Alert", JOptionPane.ERROR_MESSAGE);
        return;
        }
        try{
            
        con=DriverManager.getConnection("jdbc:ucanaccess://C:\\Users\\thofiq\\Documents\\CollegeMan.accdb");
        String Query="select Enrolment_Id,Name,D_O_B,Gender,Address,Past_Qualification,Percentage,Mobile_no from student where Enrolment_Id="+Integer.parseInt(Enr_no.getText());
        st=con.createStatement();
        rs=st.executeQuery(Query);
//        if (rs.next()==false){
//            JOptionPane.showMessageDialog(null, "No data found", "Alert", JOptionPane.ERROR_MESSAGE);
//
//        }
        if(!Pattern.matches("[0-9]{8}",Enr_no.getText())){
            
                 JOptionPane.showMessageDialog(null, "Please Enter Valid Enrollment no", "Alert", JOptionPane.ERROR_MESSAGE);
                   error=true;
                   return;
                }
        
        while(rs.next()){
            if (val==false){
                val=true;
                
            }
            pqual_text.setText(rs.getString(6));
            name_text.setText(rs.getString(2));
            per_text.setText(rs.getString(7));
            dob_text.setText(rs.getString(3));
            gender_text.setText(rs.getString(4));
            addr_text.setText(rs.getString(5));
            mob_text.setText(rs.getString(8));
            Enr_no.setEnabled(false);
        }
        
        if (val==false){
            
            JOptionPane.showMessageDialog(null, "No Data Found", "Alert", JOptionPane.ERROR_MESSAGE);

        }
        
        }
        catch(SQLException e){
            System.out.println(e.toString());
        }

    }
        public void updateStudent(){
        Boolean val=false;
        if (Enr_no.getText().isEmpty()){
        JOptionPane.showMessageDialog(null, "Please Enter Enrolment no", "Alert", JOptionPane.ERROR_MESSAGE);
        return;
        }
        try{
            
        con=DriverManager.getConnection("jdbc:ucanaccess://C:\\Users\\abc\\Documents\\CollegeMan.accdb");
        String Query="update student set Name=?,D_O_B=?,Gender=?,Address=?,Past_Qualification=?,Percentage=?,Mobile_no=? where Enrolment_Id="+Integer.parseInt(Enr_no.getText());
        prst=con.prepareStatement(Query);
       
        if(!name_text.getText().isEmpty()){
             prst.setString(1,name_text.getText());

            }else{
             JOptionPane.showMessageDialog(null, "Please Enter Name", "Alert", JOptionPane.ERROR_MESSAGE);
                error=true;
                return;
             }
              if(!dob_text.getText().isEmpty()){
                  if (Pattern.matches("^[0|1|2|3][0-9]\\/([0][0-9]|[1][0-2])\\/([0|1][0-9]{3}|[2]0[0-9]{2})$",dob_text.getText())){
                    prst.setString(2,dob_text.getText());

                  }
                  else{
                  JOptionPane.showMessageDialog(null, "Please Enter valid Date of Birth", "Alert", JOptionPane.ERROR_MESSAGE);
                error=true;
                return;
                  }

            }else{
               JOptionPane.showMessageDialog(null, "Please Enter Date of Birth", "Alert", JOptionPane.ERROR_MESSAGE);
                error=true;
                return;
              }
           if(!gender_text.getText().isEmpty()){
                           prst.setString(3,gender_text.getText());

            }else{
               JOptionPane.showMessageDialog(null, "Please Enter Gender", "Alert", JOptionPane.ERROR_MESSAGE);
                error=true;
                return;
              }
//            prst.setString(4,Gender);
            
             if(!addr_text.getText().isEmpty()){
                           prst.setString(4,addr_text.getText());

            }else{
               JOptionPane.showMessageDialog(null, "Please Enter Address", "Alert", JOptionPane.ERROR_MESSAGE);
                error=true;
                return;
              }
              if(!pqual_text.getText().isEmpty()){
                           prst.setString(5,pqual_text.getText());

            }else{
               JOptionPane.showMessageDialog(null, "Please Enter Past Qualification", "Alert", JOptionPane.ERROR_MESSAGE);
                error=true;
                return;
              }
               if(!per_text.getText().isEmpty()){
                           prst.setFloat(6,Float.parseFloat(per_text.getText()));

            }else{
               JOptionPane.showMessageDialog(null, "Please Enter Percentage", "Alert", JOptionPane.ERROR_MESSAGE);
                error=true;
                return;
              } if(!mob_text.getText().isEmpty()){
                  
                   if(!Pattern.matches("[0-9]{10}", mob_text.getText()))
                   {
                    JOptionPane.showMessageDialog(null, "Please Enter 10 Digit Valid Mobile No", "Alert", JOptionPane.ERROR_MESSAGE);
                    error=true;
                     return;
                   }else{
                        prst.setString(7,mob_text.getText());

                       
                   }
              }
            
            
            if ( error==false){
                prst.executeUpdate();
                JOptionPane.showMessageDialog(null, "Successfully Submitted", "Submitted", JOptionPane.OK_OPTION);
                name_text.setText("");
                per_text.setText("");
                dob_text.setText("");
                addr_text.setText("");
                pqual_text.setText("");
                gender_text.setText("");
                mob_text.setText("");
//                eno_text.setText("");
                

                
                
            }
            

            
//            st=con.createStatement();
//            st.execute(Query);
//            while(rs.next()){
//                System.out.println(rs.getInt(1));
//            }
        }catch(SQLException ex){
            System.out.println(ex.toString());

        }
        
//        if (rs.next()==false){
//            JOptionPane.showMessageDialog(null, "No data found", "Alert", JOptionPane.ERROR_MESSAGE);
//
//        }
        
//        while(rs.next()){
//            if (val==false){
//                val=true;
//                
//            }
//            pqual_text.setText(rs.getString(6));
//            name_text.setText(rs.getString(2));
//            per_text.setText(rs.getString(7));
//            dob_text.setText(rs.getString(3));
//            gender_text.setText(rs.getString(4));
//            addr_text.setText(rs.getString(5));
//        }
//        
//        if (val==false){
//            
//            JOptionPane.showMessageDialog(null, "No Data Found", "Alert", JOptionPane.ERROR_MESSAGE);
//
//        }
        
        

    }
    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        updateStudent();
        
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        searchStudent();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void mob_textActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mob_textActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_mob_textActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(UpdateStudent.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(UpdateStudent.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(UpdateStudent.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(UpdateStudent.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new UpdateStudent().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField Enr_no;
    private javax.swing.JTextField addr_text;
    private javax.swing.JTextField dob_text;
    private javax.swing.JTextField gender_text;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JTextField mob_text;
    private javax.swing.JTextField name_text;
    private javax.swing.JTextField per_text;
    private javax.swing.JTextField pqual_text;
    // End of variables declaration//GEN-END:variables
}
